repos:
  - repo: https://framagit.org/miya/pre-commit-hooks.git
    rev: v1.0.0
    hooks:
      - id: nocheckin
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
